ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`dashboard.69.cloudops.ucll.cloud`)
    entryPoints:
      - web
providers:
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
gateway:
  listeners:
    web:
      port: 8000
      protocol: HTTP
      namespacePolicy:
        from: All
    tcp:
      port: 33060
      protocol: TCP
      namespacePolicy:
         from: All
ports:
  tcp:
    port: 33060
    exposedPort: 33060
    protocol: TCP
  web:
    port: 8000
    exposedPort: 80
additionalArguments:
  - "--api.insecure=true"
  
# https://ragasa.medium.com/efficiently-handling-multiple-traefik-entry-points-in-kubernetes-154ad2c43247